[pytest]
minversion = 7.0
addopts = -v --tb=short
testpaths = tests,src
markers =
    get: тесты, которые посылают пустой запрос GET
    get_list: тесты про передачу параметров списком в GET
    get_params: тесты про передачу параметров в GET
    post: тесты POST запросов
    post_form: тесты POST form-data