[pytest]
minversion = 7.0
addopts = -v --tb=short
testpaths = tests,src
markers =
    get: тесты, которые посылают пустой запрос GET
    get_params: тесты про передачу параметров в GET
    post: тесты POST запросов